#ifndef ADQT_ICON_CORE_VERSION_H
#define ADQT_ICON_CORE_VERSION_H

#define ADQT_ICON_CORE_VERSION_MAJOR 2
#define ADQT_ICON_CORE_VERSION_MINOR 0
#define ADQT_ICON_CORE_VERSION_PATCH 0

#define ADQT_ICON_CORE_VERSION_STR "2.0.0"

#endif  // ADQT_ICON_CORE_VERSION_H
