// Generated by tools/generate_icon_pack.py. DO NOT EDIT.
#include "widget_icons.h"

#include <QColor>

namespace adqt::widgets::icons {

namespace {

adqt::icons::ExternalIconPackDefinition definition() {
  using namespace adqt::icons;
  ExternalIconPackDefinition result;
  result.pack = QStringLiteral("ant-design-qt");
  result.source = QStringLiteral("ant_design_qt widget-owned static SVG assets");
  result.contentHash =
      QByteArrayLiteral("fb1a49c75e20a61d5ff4ab74a687f4e79b4cd8aef8c4bfac5d29f95373efbac8");
  result.entries.reserve(1);
  result.entries.append(ExternalIconPackEntry{
      QStringLiteral("twotone"), QStringLiteral("empty-simple"), IconColorModel::ThreeTone,
      IconFit::Contain,
      IconColors().withSecondary(QColor("#E6E6E6")).withTertiary(QColor("#F5F5F5")),
      QByteArray(
          R"ADQT_SVG_0(<svg width="64" height="41" viewBox="0 0 64 41" xmlns="http://www.w3.org/2000/svg" fill="__ADQT_SLOT_PRIMARY__">
  <g transform="translate(0 1)" fill="none" fill-rule="evenodd">
    <ellipse fill="__ADQT_SLOT_TERTIARY__" cx="32" cy="33" rx="32" ry="7" />
    <g fill-rule="nonzero" stroke="__ADQT_SLOT_PRIMARY__">
      <path d="M55 12.8 44.9 1.3Q44 0 42.9 0H21.1q-1.2 0-2 1.3L9 12.8V22h46z" />
      <path d="M41.6 16c0-1.7 1-3 2.2-3H55v18.1c0 2.2-1.3 3.9-3 3.9H12c-1.7 0-3-1.7-3-3.9V13h11.2c1.2 0 2.2 1.3 2.2 3s1 2.9 2.2 2.9h14.8c1.2 0 2.2-1.4 2.2-3" fill="__ADQT_SLOT_SECONDARY__" />
    </g>
  </g>
</svg>
)ADQT_SVG_0"),
      QByteArrayLiteral("4db64c1917fd372161934c01ca1f55de400c66fc9fc14ce53644c2d107ded26f"),
      false});
  return result;
}

}  // namespace

const adqt::icons::ExternalIconPack& pack() {
  static const adqt::icons::ExternalIconPack value(definition());
  return value;
}

adqt::icons::IconPackRegistrationResult registerWith(adqt::icons::IconRegistry& registry) {
  return pack().registerWith(registry);
}

adqt::icons::IconPackRegistrationResult ensureRegistered() { return pack().ensureRegistered(); }

namespace twotone {

adqt::icons::IconRef EmptySimple(const adqt::icons::IconColors& colors) {
  return pack().icon(QStringLiteral("twotone"), QStringLiteral("empty-simple"), colors);
}

}  // namespace twotone

}  // namespace adqt::widgets::icons
